### PR TITLE
Minibuffer resize extension

### PR DESCRIPTION
**Pull request by jdtsmith**
This allow mouse or window command resizing of the vertico mini-buffer window, temporarily for the current vertico session.

### CODE REVIEW

**Comment by minad** [comment]
I tried it and I am a bit torn apart now. Maybe it makes sense to include this feature by default if it would work robustly. However this is not the case. When I drag the window, it does not resize cleanly and jumps instead. The problem is probably that vertico--exhibit will itself trigger a resizing afterwards. I think implementing this properly is more work. Why do you store the original value of vertico-count, since vertico-count is only overwritten locally in the hook? This seems not necessary. 

If we don't want to spend the time to make this entirely robust, we can also just put the following to the wiki. I agree with you that the code is a bit too small for its own extension. Basically we have this levels: Either we put it in the central package, in an extension or in the wiki. Other small hacks are also collected in the wiki, e.g., https://github.com/minad/vertico/wiki#prefix-current-candidate-with-arrow.

~~~
(defun vertico-resize--minibuffer ()
  (add-hook 'window-size-change-functions
	    (lambda (win)
	      (let ((height (window-height win)))
		(when (/= (1- height) vertico-count)
		  (setq-local vertico-count (1- height))
		  (vertico--exhibit))))
	    t t))

(advice-add #'vertico--setup :before #'vertico-resize--minibuffer)
~~~

**Comment by jdtsmith** [comment]
Good point; that was a vestige from an earlier iteration which was not setting it locally; fixed.  

I don't see the jumps you noticed.  Or rather, possibly I do, but they are about the same as the line-height jumps when resizing any given window by mouse.   Do you see pixel-perfect resizes for normal windows?   

I do note that if you remove `(vertico--exhibit)` it "still works" for mouse events, presumably due to the same call via `post-command-hook` (perhaps on mouse-release).  Maybe the double exhibit is giving you trouble?  I doubt it, because that function is called all the time.  Keyboard driven resize (like `M-10 C-x ^`) need it, otherwise they do not update.

**Comment by jdtsmith** [comment]
BTW I use grow-only for `vertico-resize`, perhaps you are using shrink and grow?  I find that is not compatible.  I can add a warning.

**Comment by minad** [comment]
I also use `grow-only`, which is the default as far as I know? For now I put your code into the wiki:

https://github.com/minad/vertico/wiki#adjust-number-of-visible-candidates-when-buffer-is-resized

Sorry for not including this as an extension currently or into core itself. It is not robust enough and I don't have the time to make it so. It is also too small as an extension, which you also pointed out right away. But we will probably revisit all these issues in the future again. Things which are collected in the wiki are not forever excluded from the package itself, I see this as a staging area. 

Vertico works quite well for me currently, so I am also going to let it rest for a while, similar to Corfu. For the near future I will probably only address severe bugs in my Emacs packages and not implementing new features. This is not unreasonable given that there has been a lot of lively actively around the ecosystem, e.g., I implemented a lot for Embark recently. You may have seen that Vertico and co also got adopted as default completion UI in Doom Emacs, which is one of the most popular Emacs distributions, the other being Spacemacs. See https://github.com/hlissner/doom-emacs/commit/c2e6db27d030f20d3aead4b2049695e4b2d942ba. Now it is time to take a bit of a step back and wait for more feedback.

**Comment by jdtsmith** [comment]
No worries.  Congrats on the Doom inclusion; will definitely bring more eyeballs!  Thanks for adding to the Wiki.  I personally have not noticed any oddities with this simple resize code (except it doesn't work with the non-default shrink-and-grow), but it's fine to revisit at a later time.  It's a minor feature anyway which I can live without (though I do find myself using it, usually with keyboard driven enlarge-window).

I do hope the very small change to allow commit-predicates in corfu to be slightly more general can make it in under the feature freeze door closing.  That tiny extra bit of generality has quickly become _essential_ to my usage of corfu.  The killer feature for me is the ability to use it to auto-commit the 1st (implicit) source what that's an exact match.  Otherwise I get way too many hanging "No match" popups (Orderless is just too powerful).  Since most people will leave corfu-commit-predicate unset, it should have very little impact.

**Comment by minad** [comment]
> I do hope the very small change to allow commit-predicates in corfu to be slightly more general can make it in under the feature freeze door closing.

I am sorry to disappoint you, but for now I don't plan to add it. Not because it is a complicated change or because I disagree with it. But it needs more thought regarding the doors opened by this change and how everything fits together. Maybe things can be solved differently. I have to think if some of the features allowed by the predicate should be made available via other means, such that they are accessible to a larger user base, who don't want to write complicated predicates. However note that I didn't close the PR, so it is on my list. But please let's not continue this discussion now.

**Pull request closed without merging**
