### PR TITLE
Document an org-refile completion problem workaround.

### PR DESCRIPTION
**Pull request by skrytebane**
Hi! I had a problem with `org-refile`. Some googling lead me to `org-outline-path-complete-in-steps`, but I thought maybe this would be nice to mention for first-time Vertico users.

### CODE REVIEW

**Comment by minad** [comment]
The workaround used for `org-tags` can be adapted for `org-refile`. It will be a bit differently since there is no named completion table like `org-tags-completion-function` in `org-olpath-completing-read`.

~~~ elisp
(defun disable-selection ()
  (when (eq minibuffer-completion-table #'org-tags-completion-function)
    (setq-local vertico-map minibuffer-local-completion-map
                completion-cycle-threshold nil
                completion-styles '(basic))))
(advice-add #'vertico--setup :before #'disable-selection)
~~~

**Comment by minad** [comment]
I have set in my config:

~~~ elisp
org-refile-use-outline-path=t
org-outline-path-complete-in-steps=nil
~~~

So the workaround you mention is indeed a reasonable configuration for completion systems like Vertico, Selectrum etc.

**Comment by minad** [comment]
I should also note: Multiple of the org completion tables are broken. For example this table here should work without any workaround with Vertico if it would be properly implemented as for example the Emacs built-in file completion table. I don't understand why the tables are not fixed upstream in Org. Probably the main contributors and maintainers of Org use default completion with default completion style settings and in those limited scenarios the tables are functioning. Furthermore there are workaround commands for Ivy and Helm, such that the original broken Org commands are not even used by many people.

**Comment by skrytebane** [comment]
I haven't really investigated this thoroughly. I used *ido-mode* before, and everything worked there, so didn't see any of this until I installed Vertico. (Which is really nice, by the way.)

Anyway, maybe there are issues on this in the org-mode-repo?

**Comment by minad** [comment]
Ido is not affected by this, since `completing-read` is not replaced by Ido. In this case here you will see a default *Completions* buffer instead, but no interactive Ido completion.

**Pull request merged**
