### PR TITLE
Add note about commands that require a match or the empty string

### PR DESCRIPTION
**Pull request by astoff**

### CODE REVIEW

**Comment by astoff** [comment]
>  Alternatively you can move the cursor to the prompt line and press RET.

This doesn't work for me on `emacs -Q` and the main branch of Vertico. Not with with up and down keys, at least.

**Comment by minad** [comment]
Ah right. Moving to the prompt line is only possible if no match is required. In principle we could allow moving to the prompt as long as the prompt is empty since the "null completion" is always allowed. I didn't add this edge case, since for most require match commands like M-x you usually never want to submit the empty input.

**Comment by astoff** [comment]
Right, that would be the most intuitive thing to do in that situation. Or you can be unreleting and let these quasi-broken commands be.

**Comment by minad** [comment]
> Right, that would be the most intuitive thing to do in that situation.

No, it is not a good thing to do since then we will allow prompt movement for *all* commands with require-match/=nil. For most it doesn't make sense to allow the null completion, e.g., M-x. Therefore there is no other way, we have to leave the quasi broken commands as is.

**Pull request merged**
