### PR TITLE
Prompt selection

### PR DESCRIPTION
**Pull request by minad**

### CODE REVIEW

**Comment by protesilaos** [comment]
Hello Daniel!  I am now trying the `prompt-selection` branch.  In terms of functionality, it seems to be doing what I would expect (though I would need more time with it).  There just are a few fairly minor user interface issues that I noticed:

1. When the prompt is focused, the line highlight extends to the edge of the window.  While Marginalia are present, this does not feel consistent.  It is natural for the candidates, which extend to the other side, but the prompt is typically shorter.  Would it be possible to not extend it?

2. The cursor "cuts" the prompt's current line highlight at its position, leaving an empty blank behind it.  This is only noticeable with `blink-cursor-mode`.  The effect is easier to discern when the cursor is not a box, but something smaller.

Screenshot from 2021-04-09 15-09-13
   
3. When you tab-complete with `vertico-insert` while using a file prompt like `~/G/e-p` you correctly expand to `~/Git/emacs-packages` if `partial-completion` is among the `completion-styles`.  If you `undo` such an expansion, you might notice a kind of slow fade-in animation.  This does not happen for regular tab-completion.

4. If the point is after the `/` in a path, marginalia annotations show up.  But if you move point before or at it, they disappear even though the completion candidates remain unchanged.

Screenshot from 2021-04-09 15-10-07
Screenshot from 2021-04-09 15-10-08

**Comment by minad** [comment]
Thank you for looking again at Vertico!

>  1.
> 
>     When the prompt is focused, the line highlight extends to the edge
>     of the window. While Marginalia are present, this does not feel
>     consistent. It is natural for the candidates, which extend to the
>     other side, but the prompt is typically shorter. Would it be
>     possible to not extend it?

Yes, this was intentional - I tried to extend all the highlights. I 
don't want to introduce a configuration option only for this.

But after trying it, I think you are actually right and it is better to 
not extend the prompt highlighting, since the highlighting also does not 
extend to the prompt and should not affect temporary messages appearing 
behind the input.

>  2.
> 
>     The cursor "cuts" the prompt's current line highlight at its
>     position, leaving an empty blank behind it. This is only noticeable
>     with |blink-cursor-mode|. The effect is easier to discern when the
>     cursor is not a box, but something smaller.

This artifact should be gone now, since I removed the prompt 
highlighting extension.

>  3.
> 
>     When you tab-complete with |vertico-insert| while using a file
>     prompt like |~/G/e-p| you correctly expand to |~/Git/emacs-packages|
>     if |partial-completion| is among the |completion-styles|. If you
>     |undo| such an expansion, you might notice a kind of slow fade-in
>     animation. This does not happen for regular tab-completion.

I am not observing this. Maybe you are using something like goggles, in 
particular an outdated version of that or something else? goggles has 
been a global minor mode before, but now it is a local minor mode.

I am not sure if you are using this, but this is just the first thing 
which came to my mind.

>  4.
> 
>     If the point is after the |/| in a path, marginalia annotations show
>     up. But if you move point before or at it, they disappear even
>     though the completion candidates remain unchanged.

I just fixed this in Marginalia. See
https://github.com/minad/marginalia/commit/95c0bb3a39e9b3db0719aa695efb36291f49e8fe.

**Comment by oantolin** [comment]
I hope I can convince @minad to undo that change to Marginalia.

**Comment by oantolin** [comment]
Ah, he already reverted!

**Comment by minad** [comment]
I had convinced myself basically immediately after pushing the "fix". I will fix Vertico, but it is less trivial than I had hoped...

**Comment by protesilaos** [comment]
Pushed to elpa: https://git.savannah.gnu.org/cgit/emacs/elpa.git/?h=externals/vertico

**Pull request merged**
