### PR TITLE
Fix instructions for IDO like behaviour

### PR DESCRIPTION
**Pull request by Zotan**
I'm not a kbd expert, but "RET" did not bind correctly for me, but <return> does.

### CODE REVIEW

**Comment by minad** [comment]
Maybe the issue is a load order problem, see https://github.com/minad/vertico/commit/eedcb847869226701acaf9a36dce0a51d1b60862. Binding return instead of RET is not a good idea, since return is the low-level key symbol.

**Comment by minad** [comment]
You can also try to add the `:bind` block directly to the vertico `use-package` declaration. In the end inspect the `vertico-map` keymap and check if the correct command is bound!

**Comment by Zotan** [comment]
`(use-package vertico-directory
  :after vertico
  :bind (:map vertico-map
              ("return" . vertico-directory-enter)
              ("DEL"      . vertico-directory-delete-char)
              ("M-DEL"    . vertico-directory-delete-word))
  ;; Tidy shadowed file names
  :hook (rfn-eshadow-update-overlay . vertico-directory-tidy))`

I get:
`(114 keymap
      (101 keymap
	   (116 keymap
		(117 keymap
		     (114 keymap
			  (110 . vertico-directory-enter))))))`

In my keymap which looks like garbage

**Comment by minad** [comment]
> In my keymap which looks like garbage

Yes, this is indeed wrong, since you bind the key "return" (r, e, t, u, r, n) which leads to these many nested prefix keymaps.

**Comment by Zotan** [comment]
Yeah, it's looks like a simple mistake in my config. I wonder where I got it from. It should have been RET not return.

Thanks!

**Pull request closed without merging**
