### PR TITLE
Add vertico-activate-functions

### PR DESCRIPTION
**Pull request by jsynacek**
A new variable called `vertico-activate-functions` is added. This variable is a list of
symbols that can be used to fine-tune which functions should actually activate the vertico
UI. It can also be a special value `(t)` that makes it activate always -- that is the
default behavior, which means it's "backward compatible".

### CODE REVIEW

**Comment by jsynacek** [comment]
The name of the new variable is kind of bad, but I couldn't really come up with anything else, because I'm just bad with names... Let me know if you'd prefer to call it something else.

**Comment by minad** [comment]
Thank you for the proposal, but I don't have the intention to offer functionality in Vertico to disable it selectively per command. Vertico is supposed to handle every completion context well. There shouldn't be a need for special casing. Note that Vertico offers `vertico-multiform-mode`, `vertico-unobtrusive-mode` and `vertico-flat-mode`, which modify the Vertico display and which can be useful if you want to avoid the minibuffer from popping up.

In which scenarios would you like to opt-out of Vertico? The addition of `vertico-activate-functions` is simple enough such that you you can just maintain the `vertico--advice` override in your user configuration.

~~~ elisp
(defun vertico--advice (&rest args)
  (minibuffer-with-setup-hook
      (if (or (eq vertico-activate-functions t)
              (memq this-command vertico-activate-functions))
          #'vertico--setup
        #'ignore)
    (apply args)))
~~~

**Comment by jsynacek** [comment]
> Vertico is supposed to handle every completion context well. There shouldn't be a need for special casing.

You seem to be assuming that Vertico has to be perfect for everyone, otherwise something is broken. That's a very simplistic view and real world users simply don't work that way. The entire Emacs breaks that assumption, by the way, otherwise there would hardly be any custom variables.

> In which scenarios would you like to opt-out of Vertico? These scenarios are interesting since then either Vertico or the affected commands need improvements.

I don't think that anything needs improvement. It's just personal preference, that's all. Two most annoying ones for me are `find-file` and hitting `i` in the Elisp info manual.

Anyway, I respect your decision. I submitted the PR "in case the author would be interested".

**Comment by minad** [comment]
> You seem to be assuming that Vertico has to be perfect for everyone, otherwise something is broken. That's a very simplistic view and real world users simply don't work that way. 

Yes, of course. I have a simplistic view about this - just to be clear, I am intentionally simplifying. But the only way I can learn about the different scenarios where something is potentially broken is by trying to make Vertico fit for every use case.

So far Vertico works very well in all scenarios I've encountered. The few scenarios where it doesn't work are documented in the README. And yes, these are mostly broken commands.

> The entire Emacs breaks that assumption, by the way, otherwise there would hardly be any custom variables.

This is also true. But in many cases I think customization variables are added over eagerly. In many cases the customization variables are not actually needed or are only needed by very very few people who could as well achieve what they want by writing a little bit of code (advices, hooks etc).

> I don't think that anything needs improvement. It's just personal preference, that's all. Two most annoying ones for me are find-file and hitting i in the Elisp info manual.

Thanks. Good to know. Some of the Info commands are indeed broken and they will hopefully get fixed in the future.

For `find-file` I like `vertico-flat-mode`. Maybe it is not for you, that's understandable. But can you pin point precisely what you don't like about Vertico for `find-file`? Did you use Vertico for longer or do you just want to activate it for a handful of commands instead of replacing the main completion UI with it? My point here is that Vertico doesn't aim to support any special preference, in particular if I have the (simplifying) opinion that Vertico works quite well by default in most cases. If you have indeed special preferences I think it is fair to ask that you just keep the small workaround in your user configuration. By not supporting any variation we end up with a simpler system overall which is also more hackable for users who have special preferences.

> Anyway, I respect your decision. I submitted the PR "in case the author would be interested".

I am thankful for your input and feedback. I hope you are still interested in trying or using my package, providing feedback or PRs. In the case of Vertico I am intentionally quite restrictive since it is supposed to be a simple and small completion UI and I make additions only step by step in a slow pace. Far reaching enhancements are mostly provided by extension packages (see the extensions directory).

**Comment by hmelman** [comment]
I did recently come across a case where I wanted this.  I was trying [le-thesaurus](https://github.com/AnselmC/le-thesaurus.el) (which is great with embark BTW) and I wanted to disable sorting for it because it generated synonyms in a useful order (most similar to less similar) and at my suggestion it added grouping (since it generates groups for synonyms based on meanings of the base word).

I think the author intends to add its own defcustom to enable grouping and explicit sorting options (see [PR#18](https://github.com/AnselmC/le-thesaurus.el/pull/18) but until then, it would be nice if vertico let me configure this command as I want.  I used multiform to set the sort function to ignore, but setting grouping just for it (I typical have grouping disabled in Vertico and wanted it enabled for this) didn't work for me.

**Comment by minad** [comment]
@hmelman Your use case doesn't seem related to what has been proposed here. You can disable/enable both sorting and grouping via vertico-multiform-mode. You can adjust vertico-sort-function, vertico-sort-override-function and vertico-group-format.

**Pull request closed without merging**
