### PR TITLE
Allow a prefix argument to movement commands

### PR DESCRIPTION
**Pull request by jakanakaevangeli**
Addresses https://github.com/minad/vertico/issues/54
- [x] vertico-next/previous -> jump by n lines
- [x] vertico-next/previous-group -> jump by n groups
- [x] vertico-scroll-up/down -> scroll by n pages
- [ ] vertico-insert -> insert nth visible candidate
- [ ] vertico-exit -> insert nth visible candidate
- [ ] vertico-save -> save nth visible candidate

For the last three, I'm willing to post a patch as well, though
https://github.com/minad/vertico/issues/57 should probably be fixed first.

How do you feel about having opt-in ability to show indices, like with
`selectrum-show-indices`? Do you feel like they would introduce too much code?
I believe that just the indices should be fine as they don't go quite as far as
avy-style selection.

If you agree to their addition, I'm willing to write a patch. I personally
believe that they would complement vertico-insert/exit prefixed with a numeric
argument quite well.

(My fsf paperwork is signed.)

### CODE REVIEW

**Comment by minad** [comment]
I am not sure I like the added complexity of this and also of numeric display arguments. For example you can refactor it such that vertico--goto-group is removed and inlined in vertico-next-group. Maybe also vertico-next can be simplified, I have to check.

Do we really need this?

**Comment by jakanakaevangeli** [comment]
> Do we really need this?

I have no strong feelings, though I personally got used to jumping to
any visible candidate with only 2 keystrokes.

> For example you can refactor it such that vertico--goto-group is
> removed and inlined in vertico-next-group.

I pushed a commit that does that.

**Comment by minad** [comment]
So which feature do you want? Avy style jumping? The scrolling feature is only aligns vertico with normal buffer navigation. But I doubt that it is very useful.

**Comment by jakanakaevangeli** [comment]
I personally want numeric args to C-n and C-p. And find them useful and
they are straight-forward to implement (this patch).

I also want numeric args to RET and TAB and numeric indices for
visualisation which visible candidate corresponds to which numeric arg.
This is less straight-forward to implement so its your call whether we
want to have this or not.

Numeric args to C-v and M-v are probably less useful and I don't use
them myself, but this patch implements them for completeness. Same goes
for M-} and M-{.

I personally do not want avy style jumping, that is, a separate command
like selectrum-quick-insert that shows letters next to candidates.

**Comment by minad** [comment]
And you have these prefix numbers on all the time? I think about this but I don't see myself using this or I feel unconvinced about this. Is this significantly faster for you than moving up/down?

**Comment by jakanakaevangeli** [comment]
There are two features being discussed here:

1) numeric args to movement commands (C-n, C-v, C-})
2) numeric args to selection commands (RET, TAB) together with visual numbers

While this patch implements 1), I have also brought 2) into this
discussion, perhaps a bit inappropriately.

> And you have these prefix numbers on all the time?

Yes, in selectrum, I have these visual numbers on all the time and I'm
quite used to simply pressing M-7 RET to choose the seventh visible
candidate, for example. This corresponds to feature 2).

Before I knew it was possible to show these prefix numbers, I was more
used to pressing M-3 C-n RET, to quickly select the third candidate
below the current one, for example. This corresponds to feature 1).

> I think about this but I don't see myself using this or I feel
> unconvinced about this.

If by this, you mean 2), that is fine. It's quite a specific feature
(last I checked, Ivy didn't have it.) There probably aren't a lot of
users who want this after all and it isn't easy to implement.

As for 1), I don't see the harm. I imagine a lot of Emacs users are used
to prefix arguments for buffer navigation with C-n/C-p, and they might
be disappointed that it doesn't work similarly in vertico, especially
given the fact that Emacs makes it quite easy to write commands with
numeric prefixes.

**Comment by minad** [comment]
Okay, I think I am fine with 1) since this is cheap to have but I am not fond of 2) here. 2) can be implemented in a user configuration by combining `vertico-next` with a numeric prefix argument and `vertico-insert`. Showing the indices is a bit more intricate, requiring advices etc. One thing I dislike about 2) is that the indices are relative to the first visible candidate line. At least I think it makes sense to wait a bit if this feature is commonly requested.

**Comment by jakanakaevangeli** [comment]
Okay, sounds fair to me.

**Comment by minad** [comment]
Merged partially. I wrote the group move command in a slightly different way.

**Comment by minad** [comment]
See also https://github.com/minad/vertico/blob/main/extensions/vertico-indexed.el

**Comment by jakanakaevangeli** [comment]
Great, thanks!

Just a minor nit, I had to apply the following patch to make it work without
errors:

```diff
diff --git a/extensions/vertico-indexed.el b/extensions/vertico-indexed.el
index 7f8a430..fb1f89a 100644
--- a/extensions/vertico-indexed.el
+++ b/extensions/vertico-indexed.el
@@ -51,10 +51,10 @@ (defun vertico-indexed--format-candidate (orig cand prefix suffix index start)
                    prefix)
            suffix index start))

-(defun vertico-indexed--handle-prefix (orig)
+(defun vertico-indexed--handle-prefix (orig &optional _arg)
   "Handle prefix argument before calling ORIG function."
   (let ((vertico--index (if current-prefix-arg
-                            (+ vertico-indexed--start (prefix-numeric-value current-prefix-arg))
+                            (+ vertico-indexed--min (prefix-numeric-value current-prefix-arg))
                           vertico--index)))
     (if (or (< vertico--index vertico-indexed--min)
             (> vertico--index vertico-indexed--max))
```

**Comment by minad** [comment]
@jakanakaevangeli Thanks, fixed in https://github.com/minad/vertico/commit/bb9ab1213d99c55e46d1caaf9214a0bedaaa6643.

**Comment by jakanakaevangeli** [comment]
Thanks.

Only one small error left, too minor and easy fix to make a new issue IMO:
Enable vertico-mode and vertico-index-mode
M-x RET
"apply: Wrong number of arguments"

**Comment by minad** [comment]
Thanks, I missed the _arg you've added.

**Pull request closed without merging**
